# Generated by Django 5.1.4 on 2025-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_category_portfolioitem_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(related_name='portfolio_items', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
